Surface inappropriate usage of a `FlagHolder` object as a runtime error
With the aim of steering users away from potential pitfalls in usage of the `FlagHolder` API, this change introduces implementation overrides for the class `__eq__` and `__bool__` methods which turn any such usage into a `TypeError` at runtime.

This is to help avoid situations where a user neglects to use the `FlagHolder.value` property in cases where they intended to, e.g.,

```
>>> SOME_FLAG = flags.DEFINE_boolean(...)
>>> if SOME_FLAG: do_something()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bool() not supported for instances of type 'FlagHolder' (did you mean to use 'FlagHolder.value' instead?)
```
PiperOrigin-RevId: 338473759
Change-Id: If3b6505a3bdca03db6d96ec7cc28e7214cb1a5e7