Fix typechecking errors that appeared under mypy release 1.16
The following errors are now in GH Actions at HEAD:

    absl/flags/_helpers.py:108: error: Argument 1 to "get" of "dict" has incompatible type "Any | None"; expected "str"  [arg-type]
    absl/flags/_helpers.py:111: error: Argument 2 to "_ModuleObjectAndName" has incompatible type "str | Any | None"; expected "str"  [arg-type]
    absl/testing/absltest.py:2745: error: Incompatible types in assignment (expression has type "str", variable has type "_T")  [assignment]

To resolve these errors more constructively, I also change the interface of `_ModuleObjectAndName`: instead of a tuple of Optionals, it's an Optional tuple now. The whole file is private, so changing the API is OK.

PiperOrigin-RevId: 766637390